INSERT INTO roles (name)
VALUES ('ROLE_USER'),
       ('ROLE_ADMIN');

INSERT INTO users (name, password, email, birth_date, balance, role_id)
values ('Wade', '$2a$10$0ZrU1zZA2gx9lBm2MQ1Id.gN7Itm8a8Xi3AComXN2CZXZzHCclh..', 'williams@mail.com', '01-01-1990', 0.5,
        1),
       ('Dave', '$2a$10$XtGZF/tA.hNaFsDN6MEKYOTcFS.52OFv0U0UZUWjCl34SgDJVenBG', 'harris@mail.com', '01-01-1990', 0.5,
        1),
       ('Seth', '$2a$10$V4WWGilNB2JWcYNVXXz5eOZAessEAuKE5znzGkUGmvJcDxvBL/mam', 'thomas@mail.com', '01-01-1990', 15.5,
        1),
       ('admin', '$2a$10$gPjW84sOushTvbyBVe/yguuirVIzQCHvlXwIizh4./xqLLKoK2HJq', 'admin@mail.com', '01-01-1990', 0.5,
        2);

INSERT INTO categories (name, rating)
values ('jeans', 5),
       ('shirts', 3),
       ('blouses', 4),
       ('shorts', 1),
       ('dresses', 2);

INSERT INTO products (name, description, price, category_id)
VALUES ('Denim Dreams',
        'Experience ultimate comfort and style with Denim Dreams. These jeans feature a relaxed fit and soft, stretchy fabric, making them your go-to choice for casual outings or lounging at home.',
        19.99, 1),
       ('Blue Ridge',
        'Embrace the timeless appeal of Blue Ridge jeans. Crafted from high-quality denim, these jeans offer a classic straight-leg fit and a rich, deep blue wash, perfect for adding a touch of sophistication to any outfit.',
        24.95, 1),
       ('Indigo Classic',
        'Elevate your denim collection with Indigo Classic jeans. Designed with a slim, flattering silhouette and a versatile medium wash, these jeans effortlessly blend comfort and fashion for everyday wear.',
        10.99, 1),
       ('Urban Edge',
        'Embrace urban chic with Urban Edge jeans. These edgy, distressed jeans boast a modern skinny fit and trendy details like ripped knees and frayed hems, adding an effortlessly cool vibe to your wardrobe.',
        9.99, 1),
       ('Vintage Vibes',
        'Step back in time with Vintage Vibes jeans. Inspired by retro fashion, these high-waisted jeans feature a relaxed, wide-leg cut and a faded, vintage wash, capturing the essence of nostalgic style.',
        15.99, 1),
       ('Midnight Wash',
        'Make a statement in Midnight Wash jeans. With their sleek dark wash and slimming silhouette, these jeans are perfect for a night out on the town or a sophisticated daytime look that exudes confidence.',
        12.30, 1),
       ('Rugged Chic',
        'Embrace a rugged yet chic look with these stylish jeans. The combination of a distressed finish, rugged details, and a slim fit creates a fashion-forward piece that effortlessly balances casual and trendy aesthetics.',
        18.5, 1),
       ('Distressed Delight',
        'Channel an effortlessly cool vibe with Distressed Delight jeans. Featuring strategic distressing, these jeans offer a contemporary slim fit and a touch of rebellious charm, adding an element of attitude to your wardrobe.',
        23.5, 1),
       ('Coastal Breeze',
        'Experience the refreshing allure of Coastal Breeze shirts. Crafted from lightweight and breathable fabric, these shirts feature a relaxed fit and vibrant coastal-inspired patterns, perfect for a casual day at the beach or a relaxed weekend getaway.',
        19.99, 2),
       ('Modern Classics',
        'Elevate your wardrobe with Modern Classics shirts. These versatile button-down shirts are designed with clean lines and a contemporary slim fit, making them suitable for both professional settings and stylish everyday wear. Available in a variety of solid colors and subtle patterns.',
        16.80, 2),
       ('Heritage Plaid',
        'Embrace timeless style with Heritage Plaid shirts. These classic plaid shirts are crafted from soft and durable fabric, offering a comfortable and stylish fit. With their rustic charm and versatile design, they are a perfect choice for casual outings or a relaxed weekend in the countryside.',
        19.70, 2),
       ('Serene Elegance',
        'Serene Elegance: Embrace a touch of sophistication with Serene Elegance blouses. These delicately crafted blouses feature a flowing silhouette, feminine details, and a subtle sheen, making them the perfect choice for a classy evening event or a refined daytime look.',
        12.99, 3),
       ('Boho Chic',
        'Channel your inner free spirit with Boho Chic blouses. These relaxed and breezy blouses showcase bohemian-inspired prints, billowing sleeves, and intricate embroidery, adding a bohemian flair to your wardrobe for a casual yet stylish ensemble.',
        8.99, 3),
       ('Modern Muse',
        'Become a style icon with Modern Muse blouses. With their contemporary designs, clean lines, and flattering cuts, these blouses effortlessly blend fashion and versatility. Whether for a day at the office or a social gathering, they will make you feel confident and empowered.',
        18.00, 3),
       ('Summer Breeze',
        'Embrace the carefree vibes of summer with Summer Breeze shorts. These lightweight and breathable shorts feature a relaxed fit, elastic waistband, and vibrant patterns, making them a perfect choice for beach trips, picnics, or casual outdoor activities.',
        3.99, 4),
       ('Sunset Serenade',
        'Embrace the beauty of golden hour with the Sunset Serenade dress. This flowing maxi dress features a captivating sunset-inspired color palette, delicate lace detailing, and a comfortable, relaxed fit, perfect for romantic evenings or special occasions.',
        110.00, 5),
       ('Gardenia Blooms',
        'Step into a blossoming garden with the Gardenia Blooms dress. Adorned with vibrant floral prints, this charming dress offers a flattering A-line silhouette, a sweetheart neckline, and a touch of feminine elegance, ideal for springtime events or garden parties.',
        78.35, 5),
       ('Moonlit Romance',
        'Experience enchanting elegance with the Moonlit Romance dress. This ethereal, floor-length gown features a delicately embellished bodice, sheer sleeves, and a flowing skirt, making it a captivating choice for formal affairs or a night of dancing under the moonlight.',
        89.99, 5),
       ('Summer Breeze',
        'Embrace the carefree spirit of summer with the Summer Breeze dress. Made from lightweight fabric and featuring a playful, off-shoulder design, this dress radiates a relaxed and bohemian vibe, perfect for beachside vacations or casual outings.',
        73.5, 5),
       ('Vintage Glamour',
        'Channel timeless allure with the Vintage Glamour dress. This chic and sophisticated dress boasts a figure-hugging silhouette, a sweetheart neckline, and intricate lace details, exuding old Hollywood glamour and making it an ideal choice for elegant evenings or formal events.',
        82.00, 5);

INSERT INTO orders (price, user_id, created_at)
VALUES (100.00, 1, CURRENT_TIMESTAMP),
       (19.99, 1, CURRENT_TIMESTAMP),
       (200.00, 2, CURRENT_TIMESTAMP),
       (25.00, 2, CURRENT_TIMESTAMP),
       (50.00, 2, CURRENT_TIMESTAMP),
       (0.30, 3, CURRENT_TIMESTAMP);

INSERT INTO carts (price, created_at, user_id)
VALUES (50.55, CURRENT_TIMESTAMP, 1),
       (10.99, CURRENT_TIMESTAMP, 2),
       (0.5, CURRENT_TIMESTAMP, 3);